#!/bin/bash

options=( 
    style=round 
    width=5.0 
    hidpi=true 
    # TokyoNight colors
    active_color=0xff7aa2f7     # blue
    inactive_color=0xff3b4261   # dark gray (bg_highlight)
) 

borders "${options[@]}"
