#!/bin/bash

find . -type f \
  ! -path '*.txt' \
  ! -path '*.json' \
  ! -path '*.MOV' \
  ! -path '*.ogg' \
  ! -path '*.mp3' \
  ! -path '*.wav' \
  ! -path '*.mp4' \
  ! -path '*.mkv' \
  ! -path '*.flv' \
  ! -path '*.avi' \
  ! -path '*.jpg' \
  ! -path '*.png' \
  ! -path '*.jpeg' \
  ! -path '*.gif' \
  ! -path '*.svg' \
  ! -path '*.ico' \
  ! -path '*.pdf' \
  ! -path '*/.mypy_cache/*' \
  ! -path '*/.mypy/*' \
  ! -path '*/__pycache__/*' \
  ! -path '*/mypy_cache/*' \
  ! -path '*/mypy/*' \
  ! -path '*/dist/*' \
  ! -path '*/build/*' \
  ! -path '*/.pytest_cache/*' \
  ! -path '*/docs/*' \
  ! -path '*/.venv/*' \
  ! -path '*/venv/*' \
  ! -path '*/.git/*' \
  ! -path '*/.gitignore' \
  ! -path '*/*.session*' \
  ! -path '*/*.log' \
  ! -path '*/*.env' \
  ! -path '*/README*' \
  ! -path '*/node_modules/*' \
  ! -path '*/poetry.lock' \
  ! -path '*/pyproject.toml' \
  ! -path '*/package-lock.json' \
  ! -path '*/yarn.lock' \
  ! -path '*/pnpm-lock.yaml' \
  ! -path '*/yarn-error.log' \
  ! -path '*/yarn-debug.log' \
  ! -path '*/package.json' \
  ! -path '*/build/*' \
  ! -path '*/dist/*' \
  ! -path '*/go.mod' \
  ! -path '*/go.sum' \
  ! -path '*/target/*' \
  ! -path '*/Cargo.toml' \
  ! -path '*/Cargo.lock' \
  -exec wc -l {} +
